apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 'mikhailmar/kuberintro_nginx:1.2'
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
          volumeMounts:
            - name: app
              mountPath: /app
      initContainers:
        - name: init-index
          image: 'busybox:1.28'
          imagePullPolicy: Always
          volumeMounts:
            - name: app
              mountPath: /app
          command:
            - sh
            - '-c'
            - 'wget -O- https://tinyurl.com/otus-k8s-intro  | sh'
      volumes:
        - name: app
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
