prometheusOperator:
  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

grafana:
  enabled: true
  defaultDashboardsEnabled: true

  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - grafana.34.68.11.248.xip.io

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    #podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool
    ruleSelector:


  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - prometheus.34.68.11.248.xip.io

alertmanager:
  alertmanagerSpec:

    tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool

  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - alertmanager.34.68.11.248.xip.io
